"""Localized copy for the ZERO LABS brochure generator.

Company-history pages mirror the company-provided milestones published on the
localized homepage, including their stated rankings, donation, and CBD records.
Other copy avoids unsupported efficacy or certification claims. Product pack
sizes follow the supplied 2026 Chinese brochure.
"""

from history_content import BRAND_HISTORY

LANGUAGES = {
    "ko": {"label": "한국어", "label_ko": "한국어", "locale": "ko-KR", "dir": "ltr", "font": "ko"},
    "en": {"label": "English", "label_ko": "English (영어)", "locale": "en-US", "dir": "ltr", "font": "en"},
    "zh-hans": {"label": "简体中文", "label_ko": "简体中文 (중국어 간체)", "locale": "zh-CN", "dir": "ltr", "font": "cjk"},
    "zh-hant": {"label": "繁體中文", "label_ko": "繁體中文 (중국어 번체)", "locale": "zh-TW", "dir": "ltr", "font": "cjk"},
    "ja": {"label": "日本語", "label_ko": "日本語 (일본어)", "locale": "ja-JP", "dir": "ltr", "font": "cjk"},
    "th": {"label": "ไทย", "label_ko": "ไทย (태국어)", "locale": "th-TH", "dir": "ltr", "font": "th"},
    "ar": {"label": "العربية", "label_ko": "العربية (아랍어)", "locale": "ar", "dir": "rtl", "font": "ar"},
}


COMPANY_CONTENT = {
    "ko": {
        "title": "주식회사 반려동행 회사소개서",
        "cover_badge": "COMPANY PROFILE · 2026",
        "cover_title": "반려견이 매일 먹는 간식의\n기준을 다시 세웁니다.",
        "cover_subtitle": "주식회사 반려동행 × ZERO LABS",
        "overview_kicker": "COMPANY AT A GLANCE",
        "overview_title": "함께 걷는 회사, 반려동행",
        "overview_body": "주식회사 반려동행은 ZERO LABS 브랜드를 운영하며 반려견 간식과 반려동물 제품을 유통합니다. 제품을 이해하기 쉬운 정보와 안정적인 파트너 운영 구조를 함께 준비합니다.",
        "metrics": [("2025", "ZERO LABS 운영 시작"), ("8", "주력 간식 라인"), ("4", "B2C · B2B 채널"), ("KR", "대한민국 인천")],
        "facts": ["회사명  주식회사 반려동행", "대표  장성환", "사업자등록번호  266-88-03624", "사업  반려견 간식 · 반려동물 제품 유통"],
        "principles_kicker": "BRAND PRINCIPLES",
        "principles_title": "ZERO LABS의 세 가지 원칙",
        "principles": [("Remove", "불필요한 요소는 덜어내고 제품 정보를 명확하게 전달합니다."), ("Balance", "제품 목적과 급여 상황을 고려해 균형 있는 라인업을 구성합니다."), ("Supply", "파트너가 지속적으로 운영할 수 있는 공급 구조를 지향합니다.")],
        "production_kicker": "MADE IN KOREA",
        "production_title": "국내 파트너와 함께 만드는 제품",
        "production": [("OEM 생산", "국내 반려동물 식품 제조 파트너와 협력해 제품을 생산합니다."), ("제품 정보", "포장 중량과 제품군을 명확히 제시해 거래 검토를 돕습니다."), ("공급 운영", "B2C와 B2B 채널을 연결해 반복 판매를 지원합니다.")],
        "portfolio_kicker": "PRODUCT PORTFOLIO",
        "portfolio_title": "8개 주력 제품 라인",
        "portfolio_subtitle": "져키 · 덴탈 · 베이커리 · 식물성 · 시리얼 카테고리",
        "products": [("고기가득 져키", "1kg · 350g"), ("영양가득 져키", "1kg · 350g"), ("베리가득 져키", "1kg · 400g"), ("치카하개", "240g"), ("굽빵", "1kg · 200g"), ("미트리스", "1kg"), ("멍스", "100g"), ("프레쉬링", "100g")],
        "history_kicker": "BRAND MILESTONES",
        "history_title": "브랜드가 걸어온 길",
        "history_subtitle": "국내 유통·프랜차이즈 입점부터 해외 수출, 대형 파트너 협업까지 — 제로랩스 브랜드가 만들어온 성과입니다. 2025년 10월, 주식회사 반려동행이 브랜드를 이어받아 운영하고 있습니다.",
        "history": BRAND_HISTORY["ko"],
        "partner_kicker": "PARTNERSHIP",
        "partner_title": "바이어가 오래 판매할 수 있는 브랜드",
        "partner_body": "펫샵과 온라인 셀러가 한 번의 판매로 끝나지 않도록, 제품력과 설명력, 그리고 재구매로 이어지는 구조를 함께 준비합니다.",
        "partner_points": [("제품력", "목적이 분명한 라인업으로, 매대와 상세페이지에서 선택받는 간식을 제안합니다."), ("설명력", "원료와 레시피의 기준을 명확히 전달해, 셀러가 자신 있게 소개할 수 있도록 돕습니다."), ("재구매 구조", "보호자가 다시 찾는 간식을 통해 거래처의 반복 판매와 안정적 운영을 지원합니다.")],
        "contact_kicker": "CONTACT",
        "contact_title": "주식회사 반려동행과 연결하세요",
        "contact_subtitle": "제품 문의와 B2B 거래 상담은 이메일 또는 카카오톡 채널로 연락해 주세요.",
        "contact_labels": ["회사 홈페이지", "ZERO LABS 공식몰", "B2B 도매몰", "카카오톡 채널", "이메일", "주소"],
        "disclosure": "본 소개서는 companimal.kr에 게시된 회사 제공 정보를 기준으로 2026년에 작성했습니다.",
    },
    "en": {
        "title": "Companimal Co., Ltd. Company Profile",
        "cover_badge": "COMPANY PROFILE · 2026",
        "cover_title": "A new standard for\neveryday dog treats.",
        "cover_subtitle": "Companimal Co., Ltd. × ZERO LABS",
        "overview_kicker": "COMPANY AT A GLANCE",
        "overview_title": "Companimal, built to walk together",
        "overview_body": "Companimal Co., Ltd. operates ZERO LABS and distributes dog treats and companion-animal products. We organize clear product information and a practical operating structure for long-term partners.",
        "metrics": [("2025", "ZERO LABS operation began"), ("8", "core treat lines"), ("4", "B2C · B2B channels"), ("KR", "Incheon, Korea")],
        "facts": ["Company  Companimal Co., Ltd.", "Representative  Seonghwan Jang", "Business registration  266-88-03624", "Business  Dog treats · pet-product distribution"],
        "principles_kicker": "BRAND PRINCIPLES",
        "principles_title": "Three principles of ZERO LABS",
        "principles": [("Remove", "Reduce what is unnecessary and communicate product information clearly."), ("Balance", "Build a balanced portfolio around product purpose and feeding occasions."), ("Supply", "Aim for a supply structure that partners can operate consistently.")],
        "production_kicker": "MADE IN KOREA",
        "production_title": "Products made with Korean partners",
        "production": [("OEM production", "We work with pet-food manufacturing partners in Korea."), ("Product information", "Pack sizes and product categories are presented clearly for trade review."), ("Supply operation", "B2C and B2B channels support repeat sales and partner access.")],
        "portfolio_kicker": "PRODUCT PORTFOLIO",
        "portfolio_title": "Eight core product lines",
        "portfolio_subtitle": "Jerky · dental · baked · plant-based · cereal categories",
        "products": [("Meat Jerky", "1 kg · 350 g"), ("Nutrition Jerky", "1 kg · 350 g"), ("Berry Jerky", "1 kg · 400 g"), ("Dental Treat", "240 g"), ("Baked Treat", "1 kg · 200 g"), ("Meatless", "1 kg"), ("Mungs", "100 g"), ("Fresh Ring", "100 g")],
        "history_kicker": "BRAND MILESTONES",
        "history_title": "The path of the brand",
        "history_subtitle": "From nationwide retail and franchise listings to exports and major partnerships — the track record of the ZERO LABS brand. Since October 2025, Companimal Co., Ltd. has carried the brand forward.",
        "history": BRAND_HISTORY["en"],
        "partner_kicker": "PARTNERSHIP",
        "partner_title": "A brand buyers can keep selling",
        "partner_body": "So pet shops and online sellers never stop at one sale, we prepare product strength, clear storytelling, and a structure that drives repurchase.",
        "partner_points": [("Product Strength", "A purposeful lineup that gets picked — on shelves and on product pages."), ("Clear Storytelling", "Clear ingredient and recipe standards, so sellers can present with confidence."), ("Repurchase Structure", "Treats pet parents come back for, supporting repeat sales and stable operations.")],
        "contact_kicker": "CONTACT",
        "contact_title": "Connect with Companimal",
        "contact_subtitle": "For product inquiries and B2B discussions, contact us by email or KakaoTalk Channel.",
        "contact_labels": ["Company website", "ZERO LABS store", "B2B wholesale", "KakaoTalk Channel", "Email", "Address"],
        "disclosure": "Prepared in 2026 from company-provided information published on companimal.kr.",
    },
    "zh-hans": {
        "title": "Companimal 公司介绍",
        "cover_badge": "公司介绍 · 2026",
        "cover_title": "重新定义狗狗\n日常零食的标准。",
        "cover_subtitle": "Companimal Co., Ltd. × ZERO LABS",
        "overview_kicker": "公司概览",
        "overview_title": "与伙伴共同前行的 Companimal",
        "overview_body": "Companimal Co., Ltd. 运营 ZERO LABS 品牌，并经销狗狗零食及宠物相关产品。我们整理清晰的产品信息与合作运营结构，支持长期合作。",
        "metrics": [("2025", "开始运营 ZERO LABS"), ("8", "核心零食系列"), ("4", "B2C · B2B 渠道"), ("KR", "韩国仁川")],
        "facts": ["公司  Companimal Co., Ltd.", "代表  Jang Seonghwan", "营业执照编号  266-88-03624", "业务  狗狗零食 · 宠物产品经销"],
        "principles_kicker": "品牌原则",
        "principles_title": "ZERO LABS 的三项原则",
        "principles": [("Remove", "减少不必要的元素，并清晰传达产品信息。"), ("Balance", "根据产品用途与喂食场景构建均衡的产品组合。"), ("Supply", "以合作伙伴可持续运营的供货结构为目标。")],
        "production_kicker": "韩国制造",
        "production_title": "与韩国合作伙伴共同生产",
        "production": [("OEM 生产", "与韩国宠物食品制造伙伴合作生产。"), ("产品信息", "清晰展示包装规格和产品类别，便于采购评估。"), ("供货运营", "连接 B2C 与 B2B 渠道，支持持续销售。")],
        "portfolio_kicker": "产品组合",
        "portfolio_title": "8 大核心产品系列",
        "portfolio_subtitle": "肉干 · 洁齿 · 烘焙 · 植物基 · 谷物类别",
        "products": [("满满肉", "1 kg · 350 g"), ("满满营养", "1 kg · 350 g"), ("满满莓果", "1 kg · 400 g"), ("洁齿零食", "240 g"), ("烘烤面包", "1 kg · 200 g"), ("植物素食条", "1 kg"), ("汪汪麦脆", "100 g"), ("缤纷麦圈", "100 g")],
        "history_kicker": "品牌里程碑",
        "history_title": "品牌发展历程",
        "history_subtitle": "从韩国零售与连锁渠道入驻，到海外出口和大型合作项目 — 这是 ZERO LABS 品牌积累的成果。自 2025 年 10 月起，品牌由 Companimal Co., Ltd. 承接运营。",
        "history": BRAND_HISTORY["zh-hans"],
        "partner_kicker": "合作伙伴",
        "partner_title": "让买家可以长期销售的品牌",
        "partner_body": "为了让宠物店和电商卖家的生意不止于一次成交，我们同时备好产品力、讲解力，以及带动复购的结构。",
        "partner_points": [("产品力", "目的明确的产品线，让零食在货架和详情页上都更容易被选中。"), ("讲解力", "清晰传达原料与配方标准，让卖家可以自信地向顾客介绍。"), ("复购结构", "打造宠物主人愿意回购的零食，支持客户的重复销售与稳定运营。")],
        "contact_kicker": "联系我们",
        "contact_title": "联系 Companimal",
        "contact_subtitle": "产品咨询与 B2B 合作，请通过电子邮件或 KakaoTalk 频道联系我们。",
        "contact_labels": ["公司官网", "ZERO LABS 官方商城", "B2B 批发商城", "KakaoTalk 频道", "电子邮件", "地址"],
        "disclosure": "本介绍根据 companimal.kr 发布的公司提供信息于 2026 年编制。",
    },
    "zh-hant": {
        "title": "Companimal 公司介紹",
        "cover_badge": "公司介紹 · 2026",
        "cover_title": "重新定義狗狗\n日常零食的標準。",
        "cover_subtitle": "Companimal Co., Ltd. × ZERO LABS",
        "overview_kicker": "公司概覽",
        "overview_title": "與夥伴同行的 Companimal",
        "overview_body": "Companimal Co., Ltd. 營運 ZERO LABS 品牌，並經銷狗狗零食及寵物相關產品。我們整理清楚的產品資訊與合作營運架構，支持長期合作。",
        "metrics": [("2025", "開始營運 ZERO LABS"), ("8", "核心零食系列"), ("4", "B2C · B2B 通路"), ("KR", "韓國仁川")],
        "facts": ["公司  Companimal Co., Ltd.", "代表  Jang Seonghwan", "營業登記編號  266-88-03624", "業務  狗狗零食 · 寵物產品經銷"],
        "principles_kicker": "品牌原則",
        "principles_title": "ZERO LABS 的三項原則",
        "principles": [("Remove", "減少不必要的元素，清楚傳達產品資訊。"), ("Balance", "依產品用途與餵食情境建立均衡的產品組合。"), ("Supply", "以合作夥伴可持續營運的供貨架構為目標。")],
        "production_kicker": "韓國製造",
        "production_title": "與韓國合作夥伴共同生產",
        "production": [("OEM 生產", "與韓國寵物食品製造夥伴合作生產。"), ("產品資訊", "清楚呈現包裝規格與產品類別，方便採購評估。"), ("供貨營運", "連結 B2C 與 B2B 通路，支持持續銷售。")],
        "portfolio_kicker": "產品組合",
        "portfolio_title": "8 大核心產品系列",
        "portfolio_subtitle": "肉乾 · 潔牙 · 烘焙 · 植物基 · 穀物類別",
        "products": [("滿滿肉", "1 kg · 350 g"), ("滿滿營養", "1 kg · 350 g"), ("滿滿莓果", "1 kg · 400 g"), ("潔牙零食", "240 g"), ("烘烤麵包", "1 kg · 200 g"), ("植物素食條", "1 kg"), ("汪汪麥脆", "100 g"), ("繽紛麥圈", "100 g")],
        "history_kicker": "品牌里程碑",
        "history_title": "品牌發展歷程",
        "history_subtitle": "從韓國零售與連鎖通路進駐，到海外出口與大型合作專案 — 這是 ZERO LABS 品牌累積的成果。自 2025 年 10 月起，品牌由 Companimal Co., Ltd. 承接營運。",
        "history": BRAND_HISTORY["zh-hant"],
        "partner_kicker": "合作夥伴",
        "partner_title": "讓買家可以長期銷售的品牌",
        "partner_body": "為了讓寵物店與電商賣家的生意不止於一次成交，我們同時備好產品力、說明力，以及帶動回購的結構。",
        "partner_points": [("產品力", "目的明確的產品線，讓零食在貨架與商品頁上都更容易被選中。"), ("說明力", "清楚傳達原料與配方標準，讓賣家可以自信地向顧客介紹。"), ("回購結構", "打造飼主願意回購的零食，支持客戶的重複銷售與穩定營運。")],
        "contact_kicker": "聯絡我們",
        "contact_title": "聯絡 Companimal",
        "contact_subtitle": "產品諮詢與 B2B 合作，請透過電子郵件或 KakaoTalk 頻道與我們聯絡。",
        "contact_labels": ["公司官網", "ZERO LABS 官方商城", "B2B 批發商城", "KakaoTalk 頻道", "電子郵件", "地址"],
        "disclosure": "本介紹依 companimal.kr 公開的公司提供資訊於 2026 年編製。",
    },
    "ja": {
        "title": "Companimal Co., Ltd. 会社案内",
        "cover_badge": "会社案内 · 2026",
        "cover_title": "毎日食べる犬用おやつの\n基準を、あらためて考える。",
        "cover_subtitle": "Companimal Co., Ltd. × ZERO LABS",
        "overview_kicker": "会社概要",
        "overview_title": "ともに歩む会社、Companimal",
        "overview_body": "Companimal Co., Ltd. は ZERO LABS ブランドを運営し、犬用おやつとペット関連商品を流通しています。分かりやすい商品情報と、長期的な取引を支える運営体制を整えています。",
        "metrics": [("2025", "ZERO LABS の運営開始"), ("8", "主力おやつライン"), ("4", "B2C · B2B チャネル"), ("KR", "韓国・仁川")],
        "facts": ["会社名  Companimal Co., Ltd.", "代表  Jang Seonghwan", "事業者登録番号  266-88-03624", "事業  犬用おやつ · ペット用品流通"],
        "principles_kicker": "ブランド原則",
        "principles_title": "ZERO LABS の3つの原則",
        "principles": [("Remove", "不要な要素を減らし、商品情報を明確に伝えます。"), ("Balance", "用途と給与シーンに合わせ、バランスのよいラインアップを構成します。"), ("Supply", "パートナーが継続運営できる供給体制を目指します。")],
        "production_kicker": "MADE IN KOREA",
        "production_title": "韓国のパートナーとつくる商品",
        "production": [("OEM 生産", "韓国のペットフード製造パートナーと協力して生産します。"), ("商品情報", "内容量と商品カテゴリーを明確に示し、仕入れ検討を支援します。"), ("供給運営", "B2C と B2B のチャネルをつなぎ、継続販売を支えます。")],
        "portfolio_kicker": "商品ポートフォリオ",
        "portfolio_title": "8つの主力商品ライン",
        "portfolio_subtitle": "ジャーキー · デンタル · ベイクド · プラントベース · シリアル",
        "products": [("ミートジャーキー", "1 kg · 350 g"), ("ニュートリションジャーキー", "1 kg · 350 g"), ("ベリージャーキー", "1 kg · 400 g"), ("デンタルトリーツ", "240 g"), ("ベイクドトリーツ", "1 kg · 200 g"), ("ミートレス", "1 kg"), ("マンス", "100 g"), ("フレッシュリング", "100 g")],
        "history_kicker": "ブランド沿革",
        "history_title": "ブランドの歩み",
        "history_subtitle": "韓国国内の流通・フランチャイズ導入から海外輸出、大手パートナーとの協業まで、ZERO LABSが築いてきた実績です。2025年10月以降、Companimal Co., Ltd.がブランドを継承し運営しています。",
        "history": BRAND_HISTORY["ja"],
        "partner_kicker": "パートナーシップ",
        "partner_title": "バイヤーが長く販売できるブランド",
        "partner_body": "ペットショップとオンラインセラーの販売が一度で終わらないよう、商品力・説明力・再購入につながる仕組みを整えます。",
        "partner_points": [("商品力", "目的が明確なラインアップで、売り場や商品ページで選ばれるおやつを提案します。"), ("説明力", "原料とレシピの基準を明確に伝え、販売者が自信を持って紹介できるよう支援します。"), ("再購入の仕組み", "飼い主が再び選ぶおやつを通じて、取引先の継続販売と安定運営を支えます。")],
        "contact_kicker": "お問い合わせ",
        "contact_title": "Companimal へのお問い合わせ",
        "contact_subtitle": "商品および B2B 取引のご相談は、メールまたは KakaoTalk チャネルへお問い合わせください。",
        "contact_labels": ["会社サイト", "ZERO LABS 公式ストア", "B2B 卸売サイト", "KakaoTalk チャネル", "メール", "所在地"],
        "disclosure": "本資料は companimal.kr に掲載された会社提供情報をもとに、2026年に作成しました。",
    },
    "th": {
        "title": "ข้อมูลบริษัท Companimal Co., Ltd.",
        "cover_badge": "ข้อมูลบริษัท · 2026",
        "cover_title": "ยกระดับมาตรฐาน\nขนมสุนัขสำหรับทุกวัน",
        "cover_subtitle": "Companimal Co., Ltd. × ZERO LABS",
        "overview_kicker": "ภาพรวมบริษัท",
        "overview_title": "Companimal บริษัทที่ก้าวไปด้วยกัน",
        "overview_body": "Companimal Co., Ltd. บริหารแบรนด์ ZERO LABS และจัดจำหน่ายขนมสุนัขกับผลิตภัณฑ์สัตว์เลี้ยง เราจัดข้อมูลสินค้าให้เข้าใจง่ายและพัฒนารูปแบบการดำเนินงานที่เหมาะกับพันธมิตรระยะยาว",
        "metrics": [("2025", "เริ่มบริหาร ZERO LABS"), ("8", "กลุ่มขนมหลัก"), ("4", "ช่องทาง B2C · B2B"), ("KR", "อินชอน เกาหลีใต้")],
        "facts": ["บริษัท  Companimal Co., Ltd.", "ผู้แทน  Jang Seonghwan", "เลขทะเบียนธุรกิจ  266-88-03624", "ธุรกิจ  ขนมสุนัข · จัดจำหน่ายผลิตภัณฑ์สัตว์เลี้ยง"],
        "principles_kicker": "หลักการของแบรนด์",
        "principles_title": "3 หลักการของ ZERO LABS",
        "principles": [("Remove", "ลดสิ่งที่ไม่จำเป็นและสื่อสารข้อมูลสินค้าอย่างชัดเจน"), ("Balance", "จัดพอร์ตสินค้าให้สมดุลตามวัตถุประสงค์และโอกาสการให้ขนม"), ("Supply", "มุ่งสร้างระบบจัดส่งที่พันธมิตรสามารถดำเนินงานได้อย่างต่อเนื่อง")],
        "production_kicker": "ผลิตในเกาหลี",
        "production_title": "สินค้าที่พัฒนาร่วมกับพันธมิตรในเกาหลี",
        "production": [("การผลิตแบบ OEM", "ร่วมงานกับพันธมิตรผู้ผลิตอาหารสัตว์เลี้ยงในเกาหลี"), ("ข้อมูลสินค้า", "แสดงขนาดบรรจุและหมวดสินค้าอย่างชัดเจนเพื่อช่วยในการพิจารณาธุรกิจ"), ("การจัดส่ง", "เชื่อมช่องทาง B2C และ B2B เพื่อสนับสนุนการขายต่อเนื่อง")],
        "portfolio_kicker": "กลุ่มผลิตภัณฑ์",
        "portfolio_title": "ผลิตภัณฑ์หลัก 8 กลุ่ม",
        "portfolio_subtitle": "เจอร์กี · เดนทัล · อบ · แพลนต์เบส · ซีเรียล",
        "products": [("มีตเจอร์กี", "1 kg · 350 g"), ("นิวทริชันเจอร์กี", "1 kg · 350 g"), ("เบอร์รีเจอร์กี", "1 kg · 400 g"), ("เดนทัลทรีต", "240 g"), ("เบกด์ทรีต", "1 kg · 200 g"), ("มีตเลส", "1 kg"), ("มังส์", "100 g"), ("เฟรชริง", "100 g")],
        "history_kicker": "หมุดหมายของแบรนด์",
        "history_title": "เส้นทางของแบรนด์",
        "history_subtitle": "ตั้งแต่การเข้าช่องทางค้าปลีกและแฟรนไชส์ในเกาหลี ไปจนถึงการส่งออกและความร่วมมือกับพันธมิตรรายใหญ่ นี่คือผลงานที่ ZERO LABS สั่งสมมา ตั้งแต่เดือนตุลาคม 2025 Companimal Co., Ltd. รับช่วงและบริหารแบรนด์",
        "history": BRAND_HISTORY["th"],
        "partner_kicker": "พันธมิตร",
        "partner_title": "แบรนด์ที่ผู้ซื้อขายต่อได้ในระยะยาว",
        "partner_body": "เพื่อให้ร้านเพ็ทช็อปและผู้ขายออนไลน์ไม่จบที่การขายครั้งเดียว เราเตรียมคุณค่าสินค้า การอธิบายที่ชัดเจน และโครงสร้างที่นำไปสู่การซื้อซ้ำ",
        "partner_points": [("คุณค่าของสินค้า", "นำเสนอขนมที่มีจุดประสงค์ชัดเจนและถูกเลือกทั้งบนชั้นวางและหน้าสินค้า"), ("ข้อมูลชัดเจน", "สื่อสารมาตรฐานวัตถุดิบและสูตรให้ชัด เพื่อให้ผู้ขายแนะนำได้อย่างมั่นใจ"), ("โครงสร้างซื้อซ้ำ", "สนับสนุนยอดขายซ้ำและการดำเนินงานที่มั่นคงด้วยขนมที่เจ้าของสัตว์เลี้ยงกลับมาซื้ออีก")],
        "contact_kicker": "ติดต่อเรา",
        "contact_title": "ติดต่อ Companimal",
        "contact_subtitle": "สอบถามสินค้าและการค้าระบบ B2B ได้ทางอีเมลหรือ KakaoTalk Channel",
        "contact_labels": ["เว็บไซต์บริษัท", "ร้าน ZERO LABS", "เว็บไซต์ขายส่ง B2B", "KakaoTalk Channel", "อีเมล", "ที่อยู่"],
        "disclosure": "จัดทำในปี 2026 จากข้อมูลที่บริษัทเผยแพร่บน companimal.kr",
    },
    "ar": {
        "title": "الملف التعريفي لشركة Companimal Co., Ltd.",
        "cover_badge": "الملف التعريفي · 2026",
        "cover_title": "نعيد تعريف معايير\nالوجبات الخفيفة اليومية للكلاب",
        "cover_subtitle": "Companimal Co., Ltd. × ZERO LABS",
        "overview_kicker": "نبذة عن الشركة",
        "overview_title": "Companimal، شركة تسير مع شركائها",
        "overview_body": "تدير شركة Companimal Co., Ltd. علامة ZERO LABS وتوزع وجبات الكلاب الخفيفة ومنتجات الحيوانات الأليفة. ننظم معلومات واضحة عن المنتجات وهيكلا عمليا يدعم الشراكات طويلة الأمد.",
        "metrics": [("2025", "بدء تشغيل ZERO LABS"), ("8", "خطوط رئيسية للمنتجات"), ("4", "قنوات B2C · B2B"), ("KR", "إنتشون، كوريا")],
        "facts": ["الشركة  Companimal Co., Ltd.", "الممثل  Jang Seonghwan", "رقم تسجيل النشاط  266-88-03624", "النشاط  وجبات خفيفة للكلاب · توزيع منتجات الحيوانات الأليفة"],
        "principles_kicker": "مبادئ العلامة",
        "principles_title": "ثلاثة مبادئ لعلامة ZERO LABS",
        "principles": [("Remove", "تقليل ما هو غير ضروري وتقديم معلومات المنتج بوضوح."), ("Balance", "بناء مجموعة متوازنة حسب غرض المنتج ومواقف التقديم."), ("Supply", "العمل على هيكل توريد يمكن للشركاء تشغيله باستمرار.")],
        "production_kicker": "صنع في كوريا",
        "production_title": "منتجات بالتعاون مع شركاء في كوريا",
        "production": [("إنتاج OEM", "نتعاون مع شركاء تصنيع أغذية الحيوانات الأليفة في كوريا."), ("معلومات المنتج", "نعرض أحجام العبوات وفئات المنتجات بوضوح لدعم مراجعة الشراء."), ("تشغيل التوريد", "نربط قنوات B2C وB2B لدعم المبيعات المتكررة.")],
        "portfolio_kicker": "مجموعة المنتجات",
        "portfolio_title": "ثمانية خطوط رئيسية",
        "portfolio_subtitle": "جيركي · عناية بالأسنان · مخبوز · نباتي · حبوب",
        "products": [("جيركي اللحم", "1 kg · 350 g"), ("جيركي التغذية", "1 kg · 350 g"), ("جيركي التوت", "1 kg · 400 g"), ("وجبة للعناية بالأسنان", "240 g"), ("وجبة مخبوزة", "1 kg · 200 g"), ("Meatless", "1 kg"), ("Mungs", "100 g"), ("Fresh Ring", "100 g")],
        "history_kicker": "محطات العلامة",
        "history_title": "مسيرة العلامة",
        "history_subtitle": "من الإدراج في قنوات التجزئة والامتياز في كوريا إلى التصدير والشراكات الكبرى، هذا هو سجل إنجازات ZERO LABS. ومنذ أكتوبر 2025، تواصل Companimal Co., Ltd. تشغيل العلامة.",
        "history": BRAND_HISTORY["ar"],
        "partner_kicker": "الشراكة",
        "partner_title": "علامة يستطيع المشترون بيعها على المدى الطويل",
        "partner_body": "حتى لا تتوقف متاجر الحيوانات والبائعون عبر الإنترنت عند عملية بيع واحدة، نبني قوة المنتج ووضوح الشرح وهيكلا يقود إلى إعادة الشراء.",
        "partner_points": [("قوة المنتج", "مجموعة واضحة الغرض تجعل الوجبات خيارا مفضلا على الرف وفي صفحات المنتج."), ("وضوح الشرح", "نوضح معايير المكونات والوصفات حتى يقدمها البائع بثقة."), ("إعادة الشراء", "ندعم المبيعات المتكررة والتشغيل المستقر بوجبات يعود إليها أصحاب الحيوانات.")],
        "contact_kicker": "تواصل معنا",
        "contact_title": "تواصل مع Companimal",
        "contact_subtitle": "للاستفسار عن المنتجات والتعاون بنظام B2B، تواصل عبر البريد الإلكتروني أو قناة KakaoTalk.",
        "contact_labels": ["موقع الشركة", "متجر ZERO LABS", "موقع الجملة B2B", "قناة KakaoTalk", "البريد الإلكتروني", "العنوان"],
        "disclosure": "أعد في 2026 استنادا إلى معلومات قدمتها الشركة ونشرتها على companimal.kr.",
    },
}


PRODUCT_CONTENT = {
    "ko": {
        "title": "ZERO LABS 제품소개서",
        "cover_tagline": "모든 반려생활의 고민을 연구합니다",
        "cover_version": "PRODUCT BROCHURE · 2026",
        "greeting_title": "인사말",
        "greeting": ["ZERO LABS는 보호자와 파트너가 제품을 쉽게 이해하고 선택할 수 있도록 반려견 간식 라인업을 연구합니다.", "주식회사 반려동행은 ZERO LABS 브랜드를 운영하며 제품군, 포장 단위, 판매 채널을 정리해 안정적인 파트너 운영을 지원합니다.", "이 소개서는 제공된 2026년 중국어 브로슈어의 제품 구성과 포장 정보를 바탕으로 제작했습니다."],
        "catalog_title": "제품 목차",
        "catalog": ["고기가득", "영양가득", "베리가득", "굽빵", "미트리스", "프레쉬링", "멍스", "치카하개", "체험팩"],
        "products": {
            "meat_1kg": ("고기가득", "육류 중심의 ZERO LABS 져키 라인입니다. 대용량 1 kg 포장으로 제공됩니다.", ["쇠고기 · 오리 · 명태 · 연어 구성", "부드러운 져키 타입", "대한민국 생산"], "1 kg · 4종"),
            "meat_350g": ("고기가득", "육류 중심의 ZERO LABS 져키 라인을 350 g 포장으로 만나볼 수 있습니다.", ["쇠고기 · 오리 · 명태 · 연어 구성", "부드러운 져키 타입", "대한민국 생산"], "350 g · 4종"),
            "nutrition_1kg": ("영양가득", "채소와 연어를 모티브로 구성한 슈퍼푸드 콘셉트의 져키 라인입니다.", ["브로콜리 · 단호박 · 토마토 · 연어 콘셉트", "3가지 제품 구성", "1 kg 포장"], "1 kg · 3종"),
            "nutrition_350g": ("영양가득", "슈퍼푸드 콘셉트의 져키 라인을 350 g 포장으로 제공합니다.", ["3가지 제품 구성", "훈련과 보상 간식으로 제안", "대한민국 생산"], "350 g · 3종"),
            "fresh_ring": ("프레쉬링", "네 가지 색상의 링 형태로 구성한 시리얼 타입 반려견 간식입니다.", ["링 형태의 시리얼 타입", "100 g 포장", "대한민국 생산"], "100 g"),
            "mungs": ("멍스", "슈퍼푸드 콘셉트를 적용한 시리얼 타입 반려견 간식입니다.", ["바삭한 시리얼 타입", "100 g 포장", "대한민국 생산"], "100 g"),
            "dental": ("치카하개", "일상적인 구강 관리 루틴에 활용할 수 있는 발포껌 타입 제품입니다.", ["3가지 제품 구성", "개별 포장", "240 g (8 g × 30개)"], "240 g · 3종"),
            "meatless": ("미트리스", "식물성 콘셉트로 구성한 부드러운 져키 타입 제품입니다.", ["고구마 · 당근 · 클로렐라 콘셉트", "1 kg 포장", "대한민국 생산"], "1 kg"),
            "berry_1kg": ("베리가득", "딸기, 블루베리, 키위 콘셉트의 과일 져키 라인입니다.", ["과일 콘셉트 제품 구성", "대용량 1 kg 포장", "대한민국 생산"], "1 kg"),
            "berry_400g": ("베리가득", "과일 콘셉트의 져키 라인을 400 g 포장으로 제공합니다.", ["딸기 · 블루베리 · 키위 콘셉트", "400 g 포장", "대한민국 생산"], "400 g"),
            "baked_1kg": ("굽빵", "오븐 베이크드 방식의 부드러운 빵 모양 반려견 간식입니다.", ["베이크드 타입", "쇠고기 콘셉트", "1 kg 포장"], "1 kg"),
            "baked_200g": ("굽빵", "오븐 베이크드 타입의 굽빵을 200 g 포장으로 제공합니다.", ["부드러운 빵 모양", "쇠고기 콘셉트", "대한민국 생산"], "200 g"),
        },
        "trial_title": "체험팩",
        "trial_intro": "주요 제품을 소용량 30 g 포장으로 먼저 만나볼 수 있습니다.",
        "contact_title": "제품 및 거래 문의",
        "contact_intro": "제품 상세 사양과 거래 조건은 공식 채널을 통해 확인해 주세요.",
        "contact_labels": ["회사 홈페이지", "카카오톡 채널", "이메일", "주소"],
        "contact_disclosure": "제품 사양과 판매 여부는 변경될 수 있습니다. 주문 전 공식 채널에서 최신 정보를 확인해 주세요.",
    },
    "en": {
        "title": "ZERO LABS Product Brochure",
        "cover_tagline": "Researching better choices for life with pets",
        "cover_version": "PRODUCT BROCHURE · 2026",
        "greeting_title": "Welcome",
        "greeting": ["ZERO LABS develops a dog-treat portfolio that pet parents and partners can understand and select with confidence.", "Companimal Co., Ltd. operates ZERO LABS and organizes product categories, pack sizes, and sales channels to support practical partner operations.", "This brochure is based on the product range and pack information shown in the supplied 2026 Chinese brochure."],
        "catalog_title": "Product Index",
        "catalog": ["Meat Jerky", "Nutrition Jerky", "Berry Jerky", "Baked Treat", "Meatless", "Fresh Ring", "Mungs", "Dental Treat", "Trial Packs"],
        "products": {
            "meat_1kg": ("Meat Jerky", "A meat-focused ZERO LABS jerky line in a value-size 1 kg pack.", ["Beef · duck · dried pollack · salmon range", "Soft jerky format", "Made in Korea"], "1 kg · 4 varieties"),
            "meat_350g": ("Meat Jerky", "The ZERO LABS meat jerky line in a practical 350 g pack.", ["Beef · duck · dried pollack · salmon range", "Soft jerky format", "Made in Korea"], "350 g · 4 varieties"),
            "nutrition_1kg": ("Nutrition Jerky", "A superfood-inspired jerky line built around vegetables and salmon.", ["Broccoli · pumpkin · tomato · salmon concepts", "Three product options", "1 kg pack"], "1 kg · 3 varieties"),
            "nutrition_350g": ("Nutrition Jerky", "The superfood-inspired jerky line in a 350 g pack.", ["Three product options", "Suitable for reward and training occasions", "Made in Korea"], "350 g · 3 varieties"),
            "fresh_ring": ("Fresh Ring", "A cereal-style dog treat formed as rings in four colors.", ["Ring-shaped cereal format", "100 g pack", "Made in Korea"], "100 g"),
            "mungs": ("Mungs", "A cereal-style dog treat with a superfood-inspired concept.", ["Crisp cereal format", "100 g pack", "Made in Korea"], "100 g"),
            "dental": ("Dental Treat", "A foamed-gum style product for a regular oral-care routine.", ["Three product options", "Individually packed", "240 g (8 g × 30 pieces)"], "240 g · 3 varieties"),
            "meatless": ("Meatless", "A soft jerky-style product with a plant-based concept.", ["Sweet potato · carrot · chlorella concept", "1 kg pack", "Made in Korea"], "1 kg"),
            "berry_1kg": ("Berry Jerky", "A fruit-inspired jerky line based on strawberry, blueberry, and kiwi concepts.", ["Assorted fruit concepts", "Value-size 1 kg pack", "Made in Korea"], "1 kg"),
            "berry_400g": ("Berry Jerky", "The fruit-inspired jerky line in a 400 g pack.", ["Strawberry · blueberry · kiwi concepts", "400 g pack", "Made in Korea"], "400 g"),
            "baked_1kg": ("Baked Treat", "A soft bread-shaped dog treat made in an oven-baked style.", ["Baked format", "Beef concept", "1 kg pack"], "1 kg"),
            "baked_200g": ("Baked Treat", "The bread-shaped baked treat in a 200 g pack.", ["Soft bread shape", "Beef concept", "Made in Korea"], "200 g"),
        },
        "trial_title": "Trial Packs",
        "trial_intro": "Explore selected products in smaller 30 g trial packs.",
        "contact_title": "Product and Trade Inquiries",
        "contact_intro": "Please confirm detailed specifications and trade terms through our official channels.",
        "contact_labels": ["Company website", "KakaoTalk Channel", "Email", "Address"],
        "contact_disclosure": "Product specifications and availability may change. Confirm current details through the official channels before ordering.",
    },
    "zh-hans": {
        "title": "ZERO LABS 产品介绍",
        "cover_tagline": "研究每一种与宠物相伴的更好选择",
        "cover_version": "产品介绍 · 2026",
        "greeting_title": "致辞",
        "greeting": ["ZERO LABS 致力于打造让宠物家长和合作伙伴都能清楚了解并安心选择的狗狗零食系列。", "Companimal Co., Ltd. 运营 ZERO LABS，并整理产品类别、包装规格与销售渠道，支持合作伙伴的实际运营。", "本介绍根据所提供的 2026 年中文产品册中的产品组合与包装信息制作。"],
        "catalog_title": "产品目录",
        "catalog": ["满满肉", "满满营养", "满满莓果", "烘烤面包", "植物素食条", "缤纷麦圈", "汪汪麦脆", "洁齿零食", "体验装"],
        "products": {
            "meat_1kg": ("满满肉", "ZERO LABS 肉类概念零食系列，提供 1 kg 大包装。", ["牛肉 · 鸭肉 · 明太鱼 · 三文鱼系列", "柔软肉条类型", "韩国制造"], "1 kg · 4种"),
            "meat_350g": ("满满肉", "ZERO LABS 肉类概念零食系列，提供 350 g 包装。", ["牛肉 · 鸭肉 · 明太鱼 · 三文鱼系列", "柔软肉条类型", "韩国制造"], "350 g · 4种"),
            "nutrition_1kg": ("满满营养", "以蔬菜和三文鱼为灵感的超级食物概念零食系列。", ["西兰花 · 南瓜 · 番茄 · 三文鱼概念", "3种产品", "1 kg 包装"], "1 kg · 3种"),
            "nutrition_350g": ("满满营养", "超级食物概念零食系列，提供 350 g 包装。", ["3种产品", "适合奖励和训练场景", "韩国制造"], "350 g · 3种"),
            "fresh_ring": ("缤纷麦圈", "以四色圆环造型呈现的谷物类型狗狗零食。", ["圆环谷物造型", "100 g 包装", "韩国制造"], "100 g"),
            "mungs": ("汪汪麦脆", "采用超级食物概念的谷物类型狗狗零食。", ["香脆谷物类型", "100 g 包装", "韩国制造"], "100 g"),
            "dental": ("洁齿零食", "适合日常口腔护理场景的发泡胶类型产品。", ["3种产品", "独立包装", "240 g (8 g × 30个)"], "240 g · 3种"),
            "meatless": ("植物素食条", "采用植物性概念的柔软肉条类型产品。", ["红薯 · 胡萝卜 · 小球藻概念", "1 kg 包装", "韩国制造"], "1 kg"),
            "berry_1kg": ("满满莓果", "以草莓、蓝莓和猕猴桃为灵感的水果零食系列。", ["多种水果概念", "1 kg 大包装", "韩国制造"], "1 kg"),
            "berry_400g": ("满满莓果", "水果概念零食系列，提供 400 g 包装。", ["草莓 · 蓝莓 · 猕猴桃概念", "400 g 包装", "韩国制造"], "400 g"),
            "baked_1kg": ("烘烤面包", "采用烘焙方式制作的柔软面包造型狗狗零食。", ["烘焙类型", "牛肉概念", "1 kg 包装"], "1 kg"),
            "baked_200g": ("烘烤面包", "面包造型烘焙零食，提供 200 g 包装。", ["柔软面包造型", "牛肉概念", "韩国制造"], "200 g"),
        },
        "trial_title": "体验装",
        "trial_intro": "部分主要产品提供 30 g 小包装，方便先行了解。",
        "contact_title": "产品与合作咨询",
        "contact_intro": "详细规格与交易条件，请通过官方渠道确认。",
        "contact_labels": ["公司官网", "KakaoTalk 频道", "电子邮件", "地址"],
        "contact_disclosure": "产品规格与销售情况可能变更。订购前请通过官方渠道确认最新信息。",
    },
    "zh-hant": {
        "title": "ZERO LABS 產品介紹",
        "cover_tagline": "研究每一種與寵物相伴的更好選擇",
        "cover_version": "產品介紹 · 2026",
        "greeting_title": "致詞",
        "greeting": ["ZERO LABS 致力於打造讓飼主與合作夥伴都能清楚了解並安心選擇的狗狗零食系列。", "Companimal Co., Ltd. 營運 ZERO LABS，並整理產品類別、包裝規格與銷售通路，支持合作夥伴的實際營運。", "本介紹依所提供的 2026 年中文產品冊之產品組合與包裝資訊製作。"],
        "catalog_title": "產品目錄",
        "catalog": ["滿滿肉", "滿滿營養", "滿滿莓果", "烘烤麵包", "植物素食條", "繽紛麥圈", "汪汪麥脆", "潔牙零食", "體驗裝"],
        "products": {
            "meat_1kg": ("滿滿肉", "ZERO LABS 肉類概念零食系列，提供 1 kg 大包裝。", ["牛肉 · 鴨肉 · 明太魚 · 鮭魚系列", "柔軟肉條類型", "韓國製造"], "1 kg · 4種"),
            "meat_350g": ("滿滿肉", "ZERO LABS 肉類概念零食系列，提供 350 g 包裝。", ["牛肉 · 鴨肉 · 明太魚 · 鮭魚系列", "柔軟肉條類型", "韓國製造"], "350 g · 4種"),
            "nutrition_1kg": ("滿滿營養", "以蔬菜與鮭魚為靈感的超級食物概念零食系列。", ["花椰菜 · 南瓜 · 番茄 · 鮭魚概念", "3種產品", "1 kg 包裝"], "1 kg · 3種"),
            "nutrition_350g": ("滿滿營養", "超級食物概念零食系列，提供 350 g 包裝。", ["3種產品", "適合獎勵與訓練情境", "韓國製造"], "350 g · 3種"),
            "fresh_ring": ("繽紛麥圈", "以四色圓環造型呈現的穀物類型狗狗零食。", ["圓環穀物造型", "100 g 包裝", "韓國製造"], "100 g"),
            "mungs": ("汪汪麥脆", "採用超級食物概念的穀物類型狗狗零食。", ["香脆穀物類型", "100 g 包裝", "韓國製造"], "100 g"),
            "dental": ("潔牙零食", "適合日常口腔照護情境的發泡膠類型產品。", ["3種產品", "獨立包裝", "240 g (8 g × 30個)"], "240 g · 3種"),
            "meatless": ("植物素食條", "採用植物性概念的柔軟肉條類型產品。", ["地瓜 · 胡蘿蔔 · 小球藻概念", "1 kg 包裝", "韓國製造"], "1 kg"),
            "berry_1kg": ("滿滿莓果", "以草莓、藍莓與奇異果為靈感的水果零食系列。", ["多種水果概念", "1 kg 大包裝", "韓國製造"], "1 kg"),
            "berry_400g": ("滿滿莓果", "水果概念零食系列，提供 400 g 包裝。", ["草莓 · 藍莓 · 奇異果概念", "400 g 包裝", "韓國製造"], "400 g"),
            "baked_1kg": ("烘烤麵包", "以烘焙方式製作的柔軟麵包造型狗狗零食。", ["烘焙類型", "牛肉概念", "1 kg 包裝"], "1 kg"),
            "baked_200g": ("烘烤麵包", "麵包造型烘焙零食，提供 200 g 包裝。", ["柔軟麵包造型", "牛肉概念", "韓國製造"], "200 g"),
        },
        "trial_title": "體驗裝",
        "trial_intro": "部分主要產品提供 30 g 小包裝，方便先行了解。",
        "contact_title": "產品與合作諮詢",
        "contact_intro": "詳細規格與交易條件，請透過官方管道確認。",
        "contact_labels": ["公司官網", "KakaoTalk 頻道", "電子郵件", "地址"],
        "contact_disclosure": "產品規格與供應情況可能變更。訂購前請透過官方管道確認最新資訊。",
    },
    "ja": {
        "title": "ZERO LABS 商品案内",
        "cover_tagline": "ペットとの暮らしに、よりよい選択を",
        "cover_version": "商品案内 · 2026",
        "greeting_title": "ごあいさつ",
        "greeting": ["ZERO LABS は、飼い主とパートナーが理解しやすく選びやすい犬用おやつのラインアップを研究しています。", "Companimal Co., Ltd. は ZERO LABS を運営し、商品カテゴリー、内容量、販売チャネルを整理してパートナーの実務を支えます。", "本資料は、ご提供いただいた2026年中国語版パンフレットの商品構成と包装情報をもとに制作しました。"],
        "catalog_title": "商品一覧",
        "catalog": ["ミートジャーキー", "ニュートリションジャーキー", "ベリージャーキー", "ベイクドトリーツ", "ミートレス", "フレッシュリング", "マンス", "デンタルトリーツ", "トライアルパック"],
        "products": {
            "meat_1kg": ("ミートジャーキー", "ZERO LABS の肉系ジャーキーライン。1 kg の大容量パックです。", ["ビーフ · ダック · スケトウダラ · サーモン", "ソフトジャーキータイプ", "韓国製造"], "1 kg · 4種"),
            "meat_350g": ("ミートジャーキー", "ZERO LABS の肉系ジャーキーラインを350 gで提供します。", ["ビーフ · ダック · スケトウダラ · サーモン", "ソフトジャーキータイプ", "韓国製造"], "350 g · 4種"),
            "nutrition_1kg": ("ニュートリションジャーキー", "野菜とサーモンをイメージしたスーパーフードコンセプトのジャーキーです。", ["ブロッコリー · パンプキン · トマト · サーモン", "3つの商品構成", "1 kg パック"], "1 kg · 3種"),
            "nutrition_350g": ("ニュートリションジャーキー", "スーパーフードコンセプトのジャーキーを350 gで提供します。", ["3つの商品構成", "ごほうびやトレーニング時に提案", "韓国製造"], "350 g · 3種"),
            "fresh_ring": ("フレッシュリング", "4色のリング形状で構成したシリアルタイプの犬用おやつです。", ["リング形状のシリアルタイプ", "100 g パック", "韓国製造"], "100 g"),
            "mungs": ("マンス", "スーパーフードコンセプトのシリアルタイプ犬用おやつです。", ["クリスピーなシリアルタイプ", "100 g パック", "韓国製造"], "100 g"),
            "dental": ("デンタルトリーツ", "毎日のオーラルケア習慣に取り入れやすい発泡ガムタイプです。", ["3つの商品構成", "個包装", "240 g (8 g × 30個)"], "240 g · 3種"),
            "meatless": ("ミートレス", "植物性コンセプトのソフトジャーキータイプです。", ["サツマイモ · ニンジン · クロレラのコンセプト", "1 kg パック", "韓国製造"], "1 kg"),
            "berry_1kg": ("ベリージャーキー", "ストロベリー、ブルーベリー、キウイをイメージしたフルーツ系ジャーキーです。", ["フルーツコンセプトの構成", "1 kg 大容量パック", "韓国製造"], "1 kg"),
            "berry_400g": ("ベリージャーキー", "フルーツコンセプトのジャーキーを400 gで提供します。", ["ストロベリー · ブルーベリー · キウイ", "400 g パック", "韓国製造"], "400 g"),
            "baked_1kg": ("ベイクドトリーツ", "オーブンベイクドタイプのやわらかなパン形犬用おやつです。", ["ベイクドタイプ", "ビーフコンセプト", "1 kg パック"], "1 kg"),
            "baked_200g": ("ベイクドトリーツ", "パン形のベイクドトリーツを200 gで提供します。", ["やわらかなパン形", "ビーフコンセプト", "韓国製造"], "200 g"),
        },
        "trial_title": "トライアルパック",
        "trial_intro": "主な商品を30 gの小容量パックでお試しいただけます。",
        "contact_title": "商品 · 取引に関するお問い合わせ",
        "contact_intro": "詳しい仕様と取引条件は、公式チャネルからご確認ください。",
        "contact_labels": ["会社サイト", "KakaoTalk チャネル", "メール", "所在地"],
        "contact_disclosure": "商品仕様と販売状況は変更される場合があります。ご注文前に公式チャネルで最新情報をご確認ください。",
    },
    "th": {
        "title": "โบรชัวร์ผลิตภัณฑ์ ZERO LABS",
        "cover_tagline": "ค้นคว้าทางเลือกที่ดีกว่าสำหรับชีวิตกับสัตว์เลี้ยง",
        "cover_version": "โบรชัวร์ผลิตภัณฑ์ · 2026",
        "greeting_title": "ยินดีต้อนรับ",
        "greeting": ["ZERO LABS พัฒนากลุ่มขนมสุนัขที่เจ้าของสัตว์เลี้ยงและพันธมิตรสามารถเข้าใจและเลือกได้ง่าย", "Companimal Co., Ltd. บริหาร ZERO LABS พร้อมจัดหมวดสินค้า ขนาดบรรจุ และช่องทางขายเพื่อสนับสนุนการดำเนินงานของพันธมิตร", "โบรชัวร์ฉบับนี้จัดทำจากกลุ่มสินค้าและข้อมูลบรรจุภัณฑ์ในโบรชัวร์ภาษาจีนปี 2026 ที่ได้รับ"],
        "catalog_title": "สารบัญผลิตภัณฑ์",
        "catalog": ["มีตเจอร์กี", "นิวทริชันเจอร์กี", "เบอร์รีเจอร์กี", "เบกด์ทรีต", "มีตเลส", "เฟรชริง", "มังส์", "เดนทัลทรีต", "แพ็กทดลอง"],
        "products": {
            "meat_1kg": ("มีตเจอร์กี", "เจอร์กีคอนเซปต์เนื้อของ ZERO LABS ในแพ็กขนาด 1 kg", ["เนื้อวัว · เป็ด · ปลาพอลล็อก · แซลมอน", "เจอร์กีเนื้อนุ่ม", "ผลิตในเกาหลี"], "1 kg · 4 แบบ"),
            "meat_350g": ("มีตเจอร์กี", "เจอร์กีคอนเซปต์เนื้อของ ZERO LABS ในแพ็กขนาด 350 g", ["เนื้อวัว · เป็ด · ปลาพอลล็อก · แซลมอน", "เจอร์กีเนื้อนุ่ม", "ผลิตในเกาหลี"], "350 g · 4 แบบ"),
            "nutrition_1kg": ("นิวทริชันเจอร์กี", "เจอร์กีคอนเซปต์ซูเปอร์ฟู้ดที่ได้แรงบันดาลใจจากผักและแซลมอน", ["บรอกโคลี · ฟักทอง · มะเขือเทศ · แซลมอน", "3 ผลิตภัณฑ์", "แพ็ก 1 kg"], "1 kg · 3 แบบ"),
            "nutrition_350g": ("นิวทริชันเจอร์กี", "เจอร์กีคอนเซปต์ซูเปอร์ฟู้ดในแพ็กขนาด 350 g", ["3 ผลิตภัณฑ์", "เหมาะสำหรับให้เป็นรางวัลหรือฝึก", "ผลิตในเกาหลี"], "350 g · 3 แบบ"),
            "fresh_ring": ("เฟรชริง", "ขนมสุนัขประเภทซีเรียลรูปวงแหวน 4 สี", ["ซีเรียลรูปวงแหวน", "แพ็ก 100 g", "ผลิตในเกาหลี"], "100 g"),
            "mungs": ("มังส์", "ขนมสุนัขประเภทซีเรียลในคอนเซปต์ซูเปอร์ฟู้ด", ["ซีเรียลกรอบ", "แพ็ก 100 g", "ผลิตในเกาหลี"], "100 g"),
            "dental": ("เดนทัลทรีต", "ผลิตภัณฑ์แบบโฟมกัมสำหรับใช้ในกิจวัตรดูแลช่องปาก", ["3 ผลิตภัณฑ์", "บรรจุแยกชิ้น", "240 g (8 g × 30 ชิ้น)"], "240 g · 3 แบบ"),
            "meatless": ("มีตเลส", "เจอร์กีเนื้อนุ่มในคอนเซปต์จากพืช", ["มันหวาน · แครอต · คลอเรลลา", "แพ็ก 1 kg", "ผลิตในเกาหลี"], "1 kg"),
            "berry_1kg": ("เบอร์รีเจอร์กี", "เจอร์กีคอนเซปต์ผลไม้จากสตรอว์เบอร์รี บลูเบอร์รี และกีวี", ["ผลิตภัณฑ์คอนเซปต์ผลไม้", "แพ็กใหญ่ 1 kg", "ผลิตในเกาหลี"], "1 kg"),
            "berry_400g": ("เบอร์รีเจอร์กี", "เจอร์กีคอนเซปต์ผลไม้ในแพ็กขนาด 400 g", ["สตรอว์เบอร์รี · บลูเบอร์รี · กีวี", "แพ็ก 400 g", "ผลิตในเกาหลี"], "400 g"),
            "baked_1kg": ("เบกด์ทรีต", "ขนมสุนัขรูปขนมปังเนื้อนุ่มในรูปแบบอบ", ["รูปแบบอบ", "คอนเซปต์เนื้อวัว", "แพ็ก 1 kg"], "1 kg"),
            "baked_200g": ("เบกด์ทรีต", "ขนมรูปขนมปังแบบอบในแพ็กขนาด 200 g", ["รูปขนมปังเนื้อนุ่ม", "คอนเซปต์เนื้อวัว", "ผลิตในเกาหลี"], "200 g"),
        },
        "trial_title": "แพ็กทดลอง",
        "trial_intro": "ทดลองผลิตภัณฑ์หลักในแพ็กขนาดเล็ก 30 g",
        "contact_title": "สอบถามสินค้าและการค้า",
        "contact_intro": "โปรดตรวจสอบรายละเอียดและเงื่อนไขการค้าผ่านช่องทางทางการของเรา",
        "contact_labels": ["เว็บไซต์บริษัท", "KakaoTalk Channel", "อีเมล", "ที่อยู่"],
        "contact_disclosure": "ข้อมูลจำเพาะและการจำหน่ายอาจเปลี่ยนแปลง โปรดตรวจสอบข้อมูลล่าสุดผ่านช่องทางทางการก่อนสั่งซื้อ",
    },
    "ar": {
        "title": "كتيب منتجات ZERO LABS",
        "cover_tagline": "نبحث عن خيارات أفضل للحياة مع الحيوانات الأليفة",
        "cover_version": "كتيب المنتجات · 2026",
        "greeting_title": "مرحبا",
        "greeting": ["تطور ZERO LABS مجموعة من وجبات الكلاب الخفيفة يسهل على أصحاب الحيوانات والشركاء فهمها واختيارها.", "تدير Companimal Co., Ltd. علامة ZERO LABS وتنظم فئات المنتجات وأحجام العبوات وقنوات البيع لدعم عمل الشركاء.", "أعد هذا الكتيب استنادا إلى مجموعة المنتجات ومعلومات العبوات في الكتيب الصيني المقدم لعام 2026."],
        "catalog_title": "فهرس المنتجات",
        "catalog": ["جيركي اللحم", "جيركي التغذية", "جيركي التوت", "وجبة مخبوزة", "Meatless", "Fresh Ring", "Mungs", "وجبة للأسنان", "عبوات تجريبية"],
        "products": {
            "meat_1kg": ("جيركي اللحم", "خط جيركي بنمط اللحم من ZERO LABS في عبوة كبيرة 1 kg.", ["لحم بقري · بط · بولوك مجفف · سلمون", "قوام جيركي طري", "صنع في كوريا"], "1 kg · 4 أنواع"),
            "meat_350g": ("جيركي اللحم", "خط جيركي بنمط اللحم من ZERO LABS في عبوة 350 g.", ["لحم بقري · بط · بولوك مجفف · سلمون", "قوام جيركي طري", "صنع في كوريا"], "350 g · 4 أنواع"),
            "nutrition_1kg": ("جيركي التغذية", "خط جيركي بمفهوم الأغذية الفائقة مستوحى من الخضار والسلمون.", ["بروكلي · قرع · طماطم · سلمون", "3 خيارات للمنتج", "عبوة 1 kg"], "1 kg · 3 أنواع"),
            "nutrition_350g": ("جيركي التغذية", "خط جيركي بمفهوم الأغذية الفائقة في عبوة 350 g.", ["3 خيارات للمنتج", "مناسب لمواقف المكافأة والتدريب", "صنع في كوريا"], "350 g · 3 أنواع"),
            "fresh_ring": ("Fresh Ring", "وجبة كلاب خفيفة على شكل حلقات حبوب بأربعة ألوان.", ["شكل حلقات من الحبوب", "عبوة 100 g", "صنع في كوريا"], "100 g"),
            "mungs": ("Mungs", "وجبة كلاب خفيفة من الحبوب بمفهوم الأغذية الفائقة.", ["قوام حبوب مقرمش", "عبوة 100 g", "صنع في كوريا"], "100 g"),
            "dental": ("وجبة للعناية بالأسنان", "منتج على هيئة علكة رغوية للاستخدام ضمن روتين العناية بالفم.", ["3 خيارات للمنتج", "تغليف فردي", "240 g (8 g × 30 قطعة)"], "240 g · 3 أنواع"),
            "meatless": ("Meatless", "منتج جيركي طري بمفهوم نباتي.", ["بطاطا حلوة · جزر · كلوريلا", "عبوة 1 kg", "صنع في كوريا"], "1 kg"),
            "berry_1kg": ("جيركي التوت", "خط جيركي بنمط الفواكه مستوحى من الفراولة والتوت الأزرق والكيوي.", ["مجموعة بنمط الفواكه", "عبوة كبيرة 1 kg", "صنع في كوريا"], "1 kg"),
            "berry_400g": ("جيركي التوت", "خط جيركي بنمط الفواكه في عبوة 400 g.", ["فراولة · توت أزرق · كيوي", "عبوة 400 g", "صنع في كوريا"], "400 g"),
            "baked_1kg": ("وجبة مخبوزة", "وجبة كلاب طرية على شكل خبز وبأسلوب مخبوز.", ["شكل مخبوز", "مفهوم اللحم البقري", "عبوة 1 kg"], "1 kg"),
            "baked_200g": ("وجبة مخبوزة", "الوجبة المخبوزة على شكل خبز في عبوة 200 g.", ["شكل خبز طري", "مفهوم اللحم البقري", "صنع في كوريا"], "200 g"),
        },
        "trial_title": "عبوات تجريبية",
        "trial_intro": "تتوفر منتجات مختارة في عبوات تجريبية صغيرة بحجم 30 g.",
        "contact_title": "استفسارات المنتجات والتجارة",
        "contact_intro": "يرجى تأكيد المواصفات التفصيلية وشروط التجارة عبر قنواتنا الرسمية.",
        "contact_labels": ["موقع الشركة", "قناة KakaoTalk", "البريد الإلكتروني", "العنوان"],
        "contact_disclosure": "قد تتغير مواصفات المنتجات وتوفرها. يرجى تأكيد أحدث المعلومات عبر القنوات الرسمية قبل الطلب.",
    },
}
