"""Homepage-faithful ZERO LABS milestones for localized company profiles."""

BRAND_HISTORY = {
    "ko": [
        ("2021", [
            "“제로랩스” 브랜드 런칭",
            "프리미엄 애견소세지 런칭",
            "야옹아멍멍해봐 OEM 납품",
            "프랜차이즈 펫마트 · 폴리파크 입점",
            "B2B 수진펫 · 딱펫 입점",
            "온라인 쿠팡 · 펫프렌즈 · 강아지대통령 · 어바웃펫 · 바잇미 입점",
            "미펫 오프라인 총판계약",
            "멍멍츄러스 총판계약",
            "K-PET 참관 (6개 부스)",
        ]),
        ("2022", [
            "쿠팡 애견간식 카테고리 TOP5 진입",
            "지에스편의점 입점",
            "스파크펫 OEM 납품",
            "전국 대리점 계약 (14개)",
            "유한양행 굿즈 개발 및 납품",
            "펫프렌즈 · 바잇미 OEM 납품",
            "온라인 SSG 입점",
            "오프라인 롯데백화점 · 코코스퀘어 · 아트박스 입점",
            "K-PET 참관 (8개 부스)",
        ]),
        ("2023", [
            "동원 F&B 뉴트리플랜 콜라보 ‘제로소세지’ 런칭",
            "태국 펫푸드 1위 ‘타이유니온’ 자체 브랜드 bellotta 총판계약",
            "제로랩스 대만 · 베트남 · 홍콩 수출",
            "콜롬비아 · 터키 불리스틱 독점계약 체결",
            "CBD 10% 오일 수입",
            "HDC신라면세점 입점",
            "‘영마진배변패드’ 런칭 · ‘PUPICE’ 총판계약",
            "펫매거진 ‘라이프앤도그’ 코브랜딩 ‘우피’ 런칭",
            "키크니 일러스트레이터 개인전 공식 후원",
            "K-PET 참관 (10개 부스)",
        ]),
        ("2024", [
            "LG화학 고양이 모래 개발 컨설팅 참여",
            "CBD 영양제 큐어올 출시",
            "트렌드쇼퍼 시즌1 상품 리뷰",
            "터키 ‘GEOCLAY’ 총판계약",
            "연성대학교 반려동물보건과 협업 및 이벤트 진행",
            "제로랩스&아베끄뚜아 콜라보 — 롯데월드몰 · 파주 신세계 아울렛 5개월 팝업",
            "유튜버 ‘킹받는 김율 일상’ 홍대 개인 팝업 공식 후원",
            "유기견 임보처 사단법인 1년간 64,762,460원 기부",
        ]),
        ("2025", [
            "제로랩스 브랜드, 주식회사 반려동행 법인으로 인수",
            "브랜드 리뉴얼 (톤앤매너 그린)",
            "제로랩스 상표권 양도",
            "쿠팡로켓 입점 승계",
            "B2B 사이트 이관",
        ]),
        ("2026", [
            "영양가득, 쿠팡 간식 판매량 TOP3 진입",
            "신제품 베리가득 · 굽빵 출시",
            "중간용량 제품 출시 (350g · 400g · 200g)",
            "제로랩스 필리핀 수출",
            "전국 대리점 재계약",
            "B2B 사이트 개설",
            "자사 홈페이지 개설",
            "농협 하나로마트 입점",
        ]),
    ],
    "en": [
        ("2021", [
            '"ZERO LABS" brand launched',
            "Premium dog sausage launched",
            "OEM supply to Yaongah-Meongmeong",
            "Listed in Pet Mart & Poly Park franchises",
            "Listed on Sujin Pet & Ddak Pet (B2B)",
            "Online launch on Coupang, Pet Friends, About Pet, Bite Me & more",
            "Offline distribution deal with Mepet",
            "Distribution deal for Meongmeong Churros",
            "K-PET fair (6 booths)",
        ]),
        ("2022", [
            "Top 5 in Coupang dog-treat category",
            "Listed in GS convenience stores",
            "OEM supply to Spark Pet",
            "14 nationwide distributor contracts",
            "Goods developed & supplied for Yuhan Corporation",
            "OEM supply to Pet Friends & Bite Me",
            "Listed on SSG online",
            "Offline: Lotte Department Store, Coco Square, Artbox",
            "K-PET fair (8 booths)",
        ]),
        ("2023", [
            '"Zero Sausage" collab with Dongwon F&B Nutriplan',
            "Distribution deal for bellotta by Thai Union, Thailand's No.1 pet food",
            "Exports to Taiwan, Vietnam & Hong Kong",
            "Exclusive bully-stick deals with Colombia & Türkiye",
            "Imported 10% CBD oil",
            "Listed in HDC Shilla Duty Free",
            "Launched pee pads · PUPICE distribution deal",
            'Co-branded "Woofy" with Life & Dog magazine',
            "Official sponsor of illustrator Keekni's exhibition",
            "K-PET fair (10 booths)",
        ]),
        ("2024", [
            "Consulted on LG Chem cat-litter development",
            "Launched CBD supplement Cureall",
            "Featured on Trend Shopper Season 1",
            "Distribution deal for GEOCLAY (Türkiye)",
            "Collaboration with Yeonsung University Pet Health Dept.",
            "5-month pop-ups at Lotte World Mall & Shinsegae Paju (with Avec Toi)",
            "Sponsored YouTuber Kim Yul's Hongdae pop-up",
            "Donated KRW 64,762,460 to a rescue-dog foster nonprofit",
        ]),
        ("2025", [
            "ZERO LABS brand acquired by Companimal Co., Ltd.",
            "Brand renewal (green tone & manner)",
            "ZERO LABS trademark transferred",
            "Coupang Rocket listing succeeded",
            "B2B site transferred",
        ]),
        ("2026", [
            "Nutrition Jerky reaches Top 3 in Coupang treat sales",
            "New Berry Jerky & Baked Treat released",
            "Mid-size packs released (350g · 400g · 200g)",
            "Exports to the Philippines",
            "Nationwide distributor contracts renewed",
            "B2B site opened",
            "Official homepage opened",
            "Listed in Nonghyup Hanaro Mart",
        ]),
    ],
    "zh-hans": [
        ("2021", [
            "“ZERO LABS” 品牌创立",
            "推出高级犬用香肠",
            "为 Yaongah-Meongmeong 提供 OEM 代工",
            "入驻连锁渠道 Pet Mart 与 Poly Park",
            "入驻 B2B 平台 Sujin Pet 与 Ddak Pet",
            "上线 Coupang、Pet Friends、About Pet、Bite Me 等电商渠道",
            "与 Mepet 签订线下总代理协议",
            "签订 Meongmeong Churros 总代理协议",
            "参展 K-PET 展会（6 个展位）",
        ]),
        ("2022", [
            "进入 Coupang 狗零食品类 TOP5",
            "入驻 GS 便利店",
            "为 Spark Pet 提供 OEM 代工",
            "签约 14 家韩国全国经销商",
            "为柳韩洋行（Yuhan）开发并供应周边产品",
            "为 Pet Friends 与 Bite Me 提供 OEM 代工",
            "上线 SSG 电商平台",
            "入驻乐天百货、Coco Square 与 Artbox 线下门店",
            "参展 K-PET 展会（8 个展位）",
        ]),
        ("2023", [
            "与东远 F&B Nutriplan 联名推出 “Zero Sausage”",
            "签订泰国第一宠物食品企业泰万盛（Thai Union）旗下品牌 bellotta 总代理协议",
            "ZERO LABS 出口至台湾、越南、香港",
            "与哥伦比亚、土耳其签订牛咬棒（Bully Stick）独家协议",
            "进口 10% 浓度 CBD 油",
            "入驻 HDC 新罗免税店",
            "推出宠物尿垫产品 · 签订 PUPICE 总代理协议",
            "与宠物杂志《Life & Dog》联名推出 “Woofy”",
            "官方赞助插画家 Keekni 个人展",
            "参展 K-PET 展会（10 个展位）",
        ]),
        ("2024", [
            "参与 LG 化学猫砂产品开发咨询",
            "推出 CBD 营养补充剂 Cureall",
            "登上《Trend Shopper》第一季产品评测",
            "签订土耳其 GEOCLAY 总代理协议",
            "与 Yeonsung 大学宠物保健专业合作并举办活动",
            "ZERO LABS × Avec Toi 联名 — 乐天世界购物中心、坡州新世界奥特莱斯 5 个月快闪店",
            "官方赞助 YouTube 博主 Kim Yul 弘大个人快闪店",
            "一年间向流浪犬寄养公益法人捐赠 64,762,460 韩元",
        ]),
        ("2025", [
            "ZERO LABS 品牌由 Companimal Co., Ltd. 收购运营",
            "品牌焕新（绿色主视觉）",
            "ZERO LABS 商标权完成转让",
            "承接 Coupang Rocket 火箭配送入驻资格",
            "B2B 网站完成迁移",
        ]),
        ("2026", [
            "营养肉干进入 Coupang 零食销量 TOP3",
            "推出新品莓果肉干与烘焙零食",
            "推出中等容量包装（350g · 400g · 200g）",
            "ZERO LABS 出口菲律宾",
            "韩国全国经销商完成续约",
            "开设 B2B 网站",
            "开设官方网站",
            "入驻农协 Hanaro Mart 超市",
        ]),
    ],
    "zh-hant": [
        ("2021", [
            "「ZERO LABS」品牌創立",
            "推出高級犬用香腸",
            "為 Yaongah-Meongmeong 提供 OEM 代工",
            "進駐連鎖通路 Pet Mart 與 Poly Park",
            "進駐 B2B 平台 Sujin Pet 與 Ddak Pet",
            "上架 Coupang、Pet Friends、About Pet、Bite Me 等電商通路",
            "與 Mepet 簽訂線下總代理合約",
            "簽訂 Meongmeong Churros 總代理合約",
            "參展 K-PET 展會（6 個攤位）",
        ]),
        ("2022", [
            "進入 Coupang 狗零食類別 TOP5",
            "進駐 GS 便利商店",
            "為 Spark Pet 提供 OEM 代工",
            "簽約 14 家韓國全國經銷商",
            "為柳韓洋行（Yuhan）開發並供應周邊商品",
            "為 Pet Friends 與 Bite Me 提供 OEM 代工",
            "上架 SSG 電商平台",
            "進駐樂天百貨、Coco Square 與 Artbox 實體門市",
            "參展 K-PET 展會（8 個攤位）",
        ]),
        ("2023", [
            "與東遠 F&B Nutriplan 聯名推出「Zero Sausage」",
            "簽訂泰國第一寵物食品企業泰萬盛（Thai Union）旗下品牌 bellotta 總代理合約",
            "ZERO LABS 出口至台灣、越南、香港",
            "與哥倫比亞、土耳其簽訂牛咬棒（Bully Stick）獨家合約",
            "進口 10% 濃度 CBD 油",
            "進駐 HDC 新羅免稅店",
            "推出寵物尿墊產品 · 簽訂 PUPICE 總代理合約",
            "與寵物雜誌《Life & Dog》聯名推出「Woofy」",
            "官方贊助插畫家 Keekni 個人展",
            "參展 K-PET 展會（10 個攤位）",
        ]),
        ("2024", [
            "參與 LG 化學貓砂產品開發顧問專案",
            "推出 CBD 營養補充品 Cureall",
            "登上《Trend Shopper》第一季產品評測",
            "簽訂土耳其 GEOCLAY 總代理合約",
            "與 Yeonsung 大學寵物保健科系合作並舉辦活動",
            "ZERO LABS × Avec Toi 聯名 — 樂天世界購物中心、坡州新世界 Outlet 5 個月快閃店",
            "官方贊助 YouTube 創作者 Kim Yul 弘大個人快閃店",
            "一年間向流浪犬中途之家公益法人捐贈 64,762,460 韓元",
        ]),
        ("2025", [
            "ZERO LABS 品牌由 Companimal Co., Ltd. 收購營運",
            "品牌煥新（綠色主視覺）",
            "ZERO LABS 商標權完成轉讓",
            "承接 Coupang Rocket 火箭配送進駐資格",
            "B2B 網站完成移轉",
        ]),
        ("2026", [
            "營養肉乾進入 Coupang 零食銷量 TOP3",
            "推出新品莓果肉乾與烘焙零食",
            "推出中容量包裝（350g · 400g · 200g）",
            "ZERO LABS 出口菲律賓",
            "韓國全國經銷商完成續約",
            "開設 B2B 網站",
            "開設官方網站",
            "進駐農協 Hanaro Mart 超市",
        ]),
    ],
    "ja": [
        ("2021", [
            "「ZERO LABS」ブランドをローンチ",
            "プレミアム犬用ソーセージを発売",
            "Yaongah-MeongmeongへOEM供給",
            "フランチャイズのPet Mart・Poly Parkに導入",
            "B2BのSujin Pet・Ddak Petに導入",
            "Coupang・Pet Friends・Gangaji Daetongryeong・About Pet・Bite Meにオンライン出店",
            "Mepetとオフライン総販売代理店契約",
            "Meongmeong Churros総販売代理店契約",
            "K-PET出展（6ブース）",
        ]),
        ("2022", [
            "Coupang犬用おやつカテゴリーTOP5入り",
            "GSコンビニエンスストアに導入",
            "Spark PetへOEM供給",
            "全国代理店14社と契約",
            "Yuhan Corporation向けグッズを開発・納品",
            "Pet Friends・Bite MeへOEM供給",
            "SSGオンラインに出店",
            "ロッテ百貨店・Coco Square・Artboxの実店舗に導入",
            "K-PET出展（8ブース）",
        ]),
        ("2023", [
            "Dongwon F&B Nutriplanとのコラボ商品「Zero Sausage」を発売",
            "タイ最大手ペットフード企業Thai Unionの自社ブランドbellotta総販売代理店契約",
            "台湾・ベトナム・香港へZERO LABSを輸出",
            "コロンビア・トルコとBully Stick独占契約を締結",
            "CBD 10%オイルを輸入",
            "HDC新羅免税店に導入",
            "ペットシーツを発売・PUPICE総販売代理店契約",
            "ペット誌Life & Dogとコーブランド「Woofy」を発売",
            "イラストレーターKeekni個展を公式協賛",
            "K-PET出展（10ブース）",
        ]),
        ("2024", [
            "LG Chemの猫砂開発コンサルティングに参加",
            "CBDサプリメントCureallを発売",
            "Trend Shopperシーズン1で商品レビュー",
            "トルコGEOCLAY総販売代理店契約",
            "Yeonsung Universityペット保健学科と協業・イベント実施",
            "ZERO LABS×Avec Toi — Lotte World Mall・Shinsegae Paju Outletで5か月間ポップアップ",
            "YouTuber Kim Yulの弘大個人ポップアップを公式協賛",
            "保護犬の預かり非営利法人へ1年間で64,762,460ウォンを寄付",
        ]),
        ("2025", [
            "ZERO LABSブランドをCompanimal Co., Ltd.が法人として買収",
            "ブランドをグリーンのトーン＆マナーへ刷新",
            "ZERO LABS商標権を譲渡",
            "Coupang Rocketの出店を承継",
            "B2Bサイトを移管",
        ]),
        ("2026", [
            "Nutrition JerkyがCoupangおやつ販売量TOP3入り",
            "新商品Berry Jerky・Baked Treatを発売",
            "中容量商品を発売（350g・400g・200g）",
            "フィリピンへZERO LABSを輸出",
            "全国代理店契約を更新",
            "B2Bサイトを開設",
            "自社ホームページを開設",
            "Nonghyup Hanaro Martに導入",
        ]),
    ],
    "th": [
        ("2021", [
            "เปิดตัวแบรนด์ ZERO LABS",
            "เปิดตัวไส้กรอกพรีเมียมสำหรับสุนัข",
            "ผลิต OEM ให้ Yaongah-Meongmeong",
            "วางจำหน่ายในแฟรนไชส์ Pet Mart และ Poly Park",
            "วางจำหน่ายในช่องทาง B2B Sujin Pet และ Ddak Pet",
            "เปิดขายออนไลน์บน Coupang, Pet Friends, Gangaji Daetongryeong, About Pet และ Bite Me",
            "ทำสัญญาตัวแทนจำหน่ายออฟไลน์กับ Mepet",
            "ทำสัญญาตัวแทนจำหน่าย Meongmeong Churros",
            "เข้าร่วมงาน K-PET จำนวน 6 บูธ",
        ]),
        ("2022", [
            "ติด TOP5 หมวดขนมสุนัขบน Coupang",
            "วางจำหน่ายในร้านสะดวกซื้อ GS",
            "ผลิต OEM ให้ Spark Pet",
            "ทำสัญญาตัวแทนจำหน่ายทั่วประเทศ 14 ราย",
            "พัฒนาและจัดส่งสินค้าพรีเมียมให้ Yuhan Corporation",
            "ผลิต OEM ให้ Pet Friends และ Bite Me",
            "เปิดขายออนไลน์บน SSG",
            "วางจำหน่ายออฟไลน์ที่ Lotte Department Store, Coco Square และ Artbox",
            "เข้าร่วมงาน K-PET จำนวน 8 บูธ",
        ]),
        ("2023", [
            "เปิดตัว Zero Sausage ร่วมกับ Dongwon F&B Nutriplan",
            "ทำสัญญาตัวแทนจำหน่าย bellotta ของ Thai Union ผู้นำอาหารสัตว์เลี้ยงอันดับ 1 ในไทย",
            "ส่งออก ZERO LABS ไปไต้หวัน เวียดนาม และฮ่องกง",
            "ทำสัญญาเอ็กซ์คลูซีฟ Bully Stick กับโคลอมเบียและตุรกี",
            "นำเข้าน้ำมัน CBD ความเข้มข้น 10%",
            "วางจำหน่ายใน HDC Shilla Duty Free",
            "เปิดตัวแผ่นรองซับและทำสัญญาตัวแทนจำหน่าย PUPICE",
            "เปิดตัว Woofy ร่วมกับนิตยสารสัตว์เลี้ยง Life & Dog",
            "ผู้สนับสนุนอย่างเป็นทางการของนิทรรศการเดี่ยว Keekni",
            "เข้าร่วมงาน K-PET จำนวน 10 บูธ",
        ]),
        ("2024", [
            "ร่วมให้คำปรึกษาการพัฒนาทรายแมวของ LG Chem",
            "เปิดตัวอาหารเสริม CBD Cureall",
            "ได้รับการรีวิวสินค้าใน Trend Shopper ซีซัน 1",
            "ทำสัญญาตัวแทนจำหน่าย GEOCLAY จากตุรกี",
            "ร่วมงานและจัดกิจกรรมกับภาควิชาสุขภาพสัตว์เลี้ยง Yeonsung University",
            "ZERO LABS × Avec Toi — ป๊อปอัป 5 เดือนที่ Lotte World Mall และ Shinsegae Paju Outlet",
            "สนับสนุนป๊อปอัปเดี่ยวที่ฮงแดของ YouTuber Kim Yul อย่างเป็นทางการ",
            "บริจาค 64,762,460 วอนใน 1 ปีแก่องค์กรไม่แสวงกำไรที่ดูแลสุนัขช่วยเหลือ",
        ]),
        ("2025", [
            "Companimal Co., Ltd. เข้าซื้อแบรนด์ ZERO LABS",
            "ปรับโฉมแบรนด์ด้วยโทนสีเขียว",
            "โอนสิทธิ์เครื่องหมายการค้า ZERO LABS",
            "รับช่วงการวางจำหน่ายผ่าน Coupang Rocket",
            "โอนย้ายเว็บไซต์ B2B",
        ]),
        ("2026", [
            "Nutrition Jerky ติด TOP3 ยอดขายขนมบน Coupang",
            "เปิดตัว Berry Jerky และ Baked Treat รุ่นใหม่",
            "เปิดตัวขนาดกลาง 350g, 400g และ 200g",
            "ส่งออก ZERO LABS ไปฟิลิปปินส์",
            "ต่อสัญญาตัวแทนจำหน่ายทั่วประเทศ",
            "เปิดเว็บไซต์ B2B",
            "เปิดเว็บไซต์บริษัท",
            "วางจำหน่ายใน Nonghyup Hanaro Mart",
        ]),
    ],
    "ar": [
        ("2021", [
            "إطلاق علامة ZERO LABS",
            "إطلاق نقانق فاخرة للكلاب",
            "توريد منتجات OEM إلى Yaongah-Meongmeong",
            "الإدراج في سلسلتي Pet Mart وPoly Park",
            "الإدراج على منصتي B2B: Sujin Pet وDdak Pet",
            "الإطلاق عبر Coupang وPet Friends وGangaji Daetongryeong وAbout Pet وBite Me",
            "اتفاقية توزيع غير متصل مع Mepet",
            "اتفاقية توزيع Meongmeong Churros",
            "المشاركة في معرض K-PET بستة أجنحة",
        ]),
        ("2022", [
            "دخول أفضل 5 في فئة وجبات الكلاب على Coupang",
            "الإدراج في متاجر GS الصغيرة",
            "توريد منتجات OEM إلى Spark Pet",
            "إبرام عقود مع 14 موزعا على مستوى كوريا",
            "تطوير وتوريد سلع لصالح Yuhan Corporation",
            "توريد منتجات OEM إلى Pet Friends وBite Me",
            "الإدراج على منصة SSG الإلكترونية",
            "الإدراج في Lotte Department Store وCoco Square وArtbox",
            "المشاركة في معرض K-PET بثمانية أجنحة",
        ]),
        ("2023", [
            "إطلاق Zero Sausage بالتعاون مع Dongwon F&B Nutriplan",
            "اتفاقية توزيع bellotta التابعة لـThai Union، الشركة الأولى لأغذية الحيوانات في تايلاند",
            "تصدير ZERO LABS إلى تايوان وفيتنام وهونغ كونغ",
            "اتفاقيات حصرية لعصي Bully Stick مع كولومبيا وتركيا",
            "استيراد زيت CBD بتركيز 10%",
            "الإدراج في HDC Shilla Duty Free",
            "إطلاق فوط تدريب واتفاقية توزيع PUPICE",
            "إطلاق Woofy بالشراكة مع مجلة Life & Dog",
            "الرعاية الرسمية لمعرض الرسام Keekni الفردي",
            "المشاركة في معرض K-PET بعشرة أجنحة",
        ]),
        ("2024", [
            "المشاركة في استشارات تطوير رمل القطط لدى LG Chem",
            "إطلاق مكمل CBD باسم Cureall",
            "مراجعة المنتجات في الموسم الأول من Trend Shopper",
            "اتفاقية توزيع GEOCLAY التركية",
            "تعاون وفعالية مع قسم صحة الحيوانات في Yeonsung University",
            "ZERO LABS × Avec Toi — متجران مؤقتان لمدة 5 أشهر في Lotte World Mall وShinsegae Paju Outlet",
            "الرعاية الرسمية لمتجر YouTuber Kim Yul المؤقت في Hongdae",
            "التبرع بمبلغ 64,762,460 وون خلال عام لمنظمة غير ربحية ترعى كلاب الإنقاذ",
        ]),
        ("2025", [
            "استحواذ Companimal Co., Ltd. على علامة ZERO LABS",
            "تجديد العلامة بهوية خضراء",
            "نقل حقوق علامة ZERO LABS التجارية",
            "استمرار الإدراج في Coupang Rocket",
            "نقل موقع B2B",
        ]),
        ("2026", [
            "دخول Nutrition Jerky أفضل 3 في مبيعات الوجبات على Coupang",
            "إطلاق Berry Jerky وBaked Treat الجديدين",
            "إطلاق عبوات متوسطة 350g و400g و200g",
            "تصدير ZERO LABS إلى الفلبين",
            "تجديد عقود الموزعين على مستوى كوريا",
            "افتتاح موقع B2B",
            "افتتاح الموقع الرسمي للشركة",
            "الإدراج في Nonghyup Hanaro Mart",
        ]),
    ],
}


EXPECTED_HISTORY_YEARS = ["2021", "2022", "2023", "2024", "2025", "2026"]
EXPECTED_HISTORY_ITEM_COUNTS = [9, 9, 10, 8, 5, 8]
